name: Build Jenkins Generic Agent

on:
  push:
    paths:
      - 'jenkins-agent-generic/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: jenkins-agent-generic
        push: true
        tags: vertisan/jenkins-agent-generic:${{ steps.date.outputs.date }}
