name: Build UBI

on:
  push:
    paths:
      - 'ubi/VERSION'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get the version
      id: version
      run: echo "::set-output name=version::$(cat ubi/VERSION)"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ubi
        push: true
        tags: vertisan/ubi:${{ steps.version.outputs.version }}
